import "../styles/globals.css";
import Head from "next/head";
import type { AppProps } from "next/app";
import "aos/dist/aos.css";
import { useEffect } from "react";
import Aos from "aos";

export default function App({ Component, pageProps }: AppProps) {
  useEffect(() => {
    Aos.init({
      offset: 200,
      duration: 600,
      easing: "ease-in-sine",
      delay: 100,
    });
  }, []);
  return (
    <>
      <Head>
        <title>Morenikejis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}
