import Head from 'next/head'
import React from 'react'
import { Space_Grotesk } from '@next/font/google'

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] })

const PageWrapper = ({children}:{children: React.ReactNode}) => {
  return (
    <>
        <style jsx global>{`
            html {
            font-family: ${spaceGrotesk.style.fontFamily};
            }
            body{
              background-color: #151515;
            }
        `}</style>
        <Head>
            <title>Morenikejis Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {children}
    </>
  )
}

export default PageWrapper